Removing repro_localstack_1 ... 
[1A[2KRemoving repro_localstack_1 ... [32mdone[0m[1BRemoving network repro_default
Creating network "repro_default" with the default driver
Creating repro_localstack_1 ... 
[1A[2KCreating repro_localstack_1 ... [32mdone[0m[1BAttaching to repro_localstack_1
[36mlocalstack_1  |[0m Waiting for all LocalStack services to be ready
[36mlocalstack_1  |[0m 2020-05-21 22:05:29,320 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
[36mlocalstack_1  |[0m 2020-05-21 22:05:29,322 INFO supervisord started with pid 13
[36mlocalstack_1  |[0m 2020-05-21 22:05:30,324 INFO spawned: 'dashboard' with pid 19
[36mlocalstack_1  |[0m 2020-05-21 22:05:30,325 INFO spawned: 'infra' with pid 20
[36mlocalstack_1  |[0m 2020-05-21 22:05:30,329 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
[36mlocalstack_1  |[0m (. .venv/bin/activate; bin/localstack web)
[36mlocalstack_1  |[0m 2020-05-21T22:05:31:DEBUG:bootstrap.py: Loading plugins - scope "commands", module "localstack_ext": <function register_localstack_commands at 0x7fda4216b550>
[36mlocalstack_1  |[0m (. .venv/bin/activate; exec bin/localstack start --host)
[36mlocalstack_1  |[0m 2020-05-21T22:05:31:DEBUG:bootstrap.py: Loading plugins - scope "commands", module "localstack_ext": <function register_localstack_commands at 0x7f07ef1db550>
[36mlocalstack_1  |[0m LocalStack version: 0.11.1
[36mlocalstack_1  |[0m 2020-05-21T22:05:31:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext": <function register_localstack_plugins at 0x7fda4251e550>
[36mlocalstack_1  |[0m 2020-05-21T22:05:31:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7fda4216b5e0>
[36mlocalstack_1  |[0m LocalStack version: 0.11.1
[36mlocalstack_1  |[0m Starting local dev environment. CTRL-C to quit.
[36mlocalstack_1  |[0m 2020-05-21T22:05:31:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext": <function register_localstack_plugins at 0x7f07ef58e550>
[36mlocalstack_1  |[0m 2020-05-21 22:05:32,320 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[36mlocalstack_1  |[0m 2020-05-21T22:05:33:INFO:localstack.utils.common: Unable to store key/cert files for custom SSL certificate: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem.key'
[36mlocalstack_1  |[0m 2020-05-21T22:05:34:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
[36mlocalstack_1  |[0m 2020-05-21T22:05:34:DEBUG:asyncio: Using selector: EpollSelector
[36mlocalstack_1  |[0m Waiting for all LocalStack services to be ready
[36mlocalstack_1  |[0m 2020-05-21T22:05:38:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7f07ef1db5e0>
[36mlocalstack_1  |[0m 2020-05-21T22:05:38:DEBUG:bootstrap.py: Plugin loading took 7.021615028381348 sec
[36mlocalstack_1  |[0m Starting mock STS service in http ports 443 (recommended) and 4592 (deprecated)...
[36mlocalstack_1  |[0m 2020-05-21T22:05:40:INFO:localstack.multiserver: Starting multi API server process on port 51492
[36mlocalstack_1  |[0m Starting mock SES service in http ports 443 (recommended) and 4579 (deprecated)...
[36mlocalstack_1  |[0m Starting DNS servers (tcp/udp port 53 on 0.0.0.0)...
[36mlocalstack_1  |[0m Starting edge router (http port 4566)...
[36mlocalstack_1  |[0m Starting edge router (https port 443)...
[36mlocalstack_1  |[0m Starting mock API Gateway service in http ports 443 (recommended) and 4567 (deprecated)...
[36mlocalstack_1  |[0m Starting mock CloudFormation service in http ports 443 (recommended) and 4581 (deprecated)...
[36mlocalstack_1  |[0m Starting mock IAM service in http ports 443 (recommended) and 4593 (deprecated)...
[36mlocalstack_1  |[0m Starting mock Lambda service in http ports 443 (recommended) and 4574 (deprecated)...
[36mlocalstack_1  |[0m Starting mock CloudWatch Logs service in http ports 443 (recommended) and 4586 (deprecated)...
[36mlocalstack_1  |[0m Starting mock S3 service in http ports 443 (recommended) and 4572 (deprecated)...
[36mlocalstack_1  |[0m Starting mock SNS service in http ports 443 (recommended) and 4575 (deprecated)...
[36mlocalstack_1  |[0m Starting mock SQS service in http ports 443 (recommended) and 4576 (deprecated)...
[36mlocalstack_1  |[0m Starting mock SSM service in http ports 443 (recommended) and 4583 (deprecated)...
[36mlocalstack_1  |[0m 22:05:42.106 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.15.5) ...
[36mlocalstack_1  |[0m 2020-05-21 22:05:41,426:API:  * Running on http://0.0.0.0:4592/ (Press CTRL+C to quit)
[36mlocalstack_1  |[0m 2020-05-21 22:05:41,426:API:  * Running on http://0.0.0.0:4592/ (Press CTRL+C to quit)
[36mlocalstack_1  |[0m 2020-05-21 22:05:41,426:API:  * Running on http://0.0.0.0:4592/ (Press CTRL+C to quit)
[36mlocalstack_1  |[0m 2020-05-21 22:05:41,457:API:  * Running on http://0.0.0.0:4533/ (Press CTRL+C to quit)
[36mlocalstack_1  |[0m 2020-05-21 22:05:41,457:API:  * Running on http://0.0.0.0:4533/ (Press CTRL+C to quit)
[36mlocalstack_1  |[0m 2020-05-21 22:05:41,457:API:  * Running on http://0.0.0.0:4533/ (Press CTRL+C to quit)
[36mlocalstack_1  |[0m 2020-05-21 22:05:41,486:API:  * Running on http://0.0.0.0:35409/ (Press CTRL+C to quit)
[36mlocalstack_1  |[0m 2020-05-21 22:05:41,486:API:  * Running on http://0.0.0.0:35409/ (Press CTRL+C to quit)
[36mlocalstack_1  |[0m 2020-05-21 22:05:41,486:API:  * Running on http://0.0.0.0:35409/ (Press CTRL+C to quit)
[36mlocalstack_1  |[0m 2020-05-21 22:05:41,514:API:  * Running on http://0.0.0.0:47087/ (Press CTRL+C to quit)
[36mlocalstack_1  |[0m 2020-05-21 22:05:41,514:API:  * Running on http://0.0.0.0:47087/ (Press CTRL+C to quit)
[36mlocalstack_1  |[0m 2020-05-21 22:05:41,514:API:  * Running on http://0.0.0.0:47087/ (Press CTRL+C to quit)
[36mlocalstack_1  |[0m 22:05:42.523 [elasticmq-akka.actor.default-dispatcher-5] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
[36mlocalstack_1  |[0m Waiting for all LocalStack services to be ready
[36mlocalstack_1  |[0m 22:05:43.381 [elasticmq-akka.actor.default-dispatcher-6] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:37471, visible server address http://9565ff46d70a:4576
[36mlocalstack_1  |[0m 22:05:43.381 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.15.5) started in 1737 ms ===
[36mlocalstack_1  |[0m 22:05:44.587 [elasticmq-akka.actor.default-dispatcher-8] INFO  o.elasticmq.actor.QueueManagerActor - Creating queue QueueData(us-east-1_pdfs-to-render,MillisVisibilityTimeout(30000),PT0S,PT0S,2020-05-21T22:05:44.559Z,2020-05-21T22:05:44.559Z,None,false,false,None,None,Map())
[36mlocalstack_1  |[0m Ready.
[36mlocalstack_1  |[0m 2020-05-21T22:05:52:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response for CloudFormation action "DescribeStacks" (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id repro-dev does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
[36mlocalstack_1  |[0m 2020-05-21T22:05:52:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:repro-dev-render-pdfs
[36mlocalstack_1  |[0m 2020-05-21T22:05:52:DEBUG:localstack.services.cloudformation.cloudformation_listener: Download CloudFormation template content from local S3: serverless-deployments - serverless/repro/dev/1590098751914-2020-05-21T22:05:51.914Z/compiled-cloudformation-template.json
[36mlocalstack_1  |[0m 2020-05-21T22:05:52:DEBUG:localstack.services.cloudformation.cloudformation_listener: Download CloudFormation template content from local S3: serverless-deployments - serverless/repro/dev/1590098751914-2020-05-21T22:05:51.914Z/compiled-cloudformation-template.json
[36mlocalstack_1  |[0m 2020-05-21T22:05:52:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource repro-dev/RenderDashpdfsLogGroup: None
[36mlocalstack_1  |[0m 2020-05-21T22:05:52:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False, exists=False, updateable=False): {'Type': 'AWS::Logs::LogGroup', 'Properties': {'LogGroupName': '/aws/lambda/repro-dev-render-pdfs'}}
[36mlocalstack_1  |[0m 2020-05-21T22:05:52:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "Logs::LogGroup" id "RenderDashpdfsLogGroup"
[36mlocalstack_1  |[0m 2020-05-21T22:05:52:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "Logs::LogGroup" in region us-east-1: create_log_group {'logGroupName': '/aws/lambda/repro-dev-render-pdfs'}
[36mlocalstack_1  |[0m 2020-05-21T22:05:52:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource repro-dev/RenderDashpdfsLambdaFunction: None
[36mlocalstack_1  |[0m 2020-05-21T22:05:52:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:repro-dev-render-pdfs
[36mlocalstack_1  |[0m 2020-05-21T22:05:52:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False, exists=False, updateable=False): {'Type': 'AWS::Lambda::Function', 'Properties': {'Code': {'S3Bucket': 'serverless-deployments', 'S3Key': 'serverless/repro/dev/1590098751914-2020-05-21T22:05:51.914Z/render-pdfs.zip'}, 'FunctionName': 'repro-dev-render-pdfs', 'Handler': 'pdfs.render', 'MemorySize': 1024, 'Role': 'arn:aws:iam::000000000000:role/render-pdfs', 'Runtime': 'nodejs12.x', 'Timeout': 6}, 'DependsOn': ['RenderDashpdfsLogGroup']}
[36mlocalstack_1  |[0m 2020-05-21T22:05:52:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "Lambda::Function" id "RenderDashpdfsLambdaFunction"
[36mlocalstack_1  |[0m 2020-05-21T22:05:52:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "Lambda::Function" in region us-east-1: create_function {'FunctionName': 'repro-dev-render-pdfs', 'Runtime': 'nodejs12.x', 'Role': 'arn:aws:iam::000000000000:role/render-pdfs', 'Handler': 'pdfs.render', 'Code': {'S3Bucket': 'serverless-deployments', 'S3Key': 'serverless/repro/dev/1590098751914-2020-05-21T22:05:51.914Z/render-pdfs.zip'}, 'Timeout': 6, 'MemorySize': 1024}
[36mlocalstack_1  |[0m 2020-05-21T22:05:53:WARNING:urllib3.connectionpool: Connection pool is full, discarding connection: 9565ff46d70a
[36mlocalstack_1  |[0m 2020-05-21T22:05:53:WARNING:urllib3.connectionpool: Connection pool is full, discarding connection: 9565ff46d70a
[36mlocalstack_1  |[0m 2020-05-21T22:05:53:WARNING:urllib3.connectionpool: Connection pool is full, discarding connection: 9565ff46d70a
[36mlocalstack_1  |[0m 2020-05-21T22:05:54:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource repro-dev/RenderDashpdfsLambdaVersionTqQYalVJPCEUm5jbsO5AqshiuAVsNhivtZ9zyTpeYc: None
[36mlocalstack_1  |[0m 2020-05-21T22:05:54:DEBUG:localstack.services.cloudformation.cloudformation_starter: Resource RenderDashpdfsLambdaVersionTqQYalVJPCEUm5jbsO5AqshiuAVsNhivtZ9zyTpeYc need not be deployed (is_updateable=False): {'Type': 'AWS::Lambda::Version', 'DeletionPolicy': 'Retain', 'Properties': {'FunctionName': 'repro-dev-render-pdfs', 'CodeSha256': '4C1K9BbFO5zpOzAhNJ2AW/h72w8sluz6KXKVgm7zDDI='}} True
[36mlocalstack_1  |[0m 2020-05-21T22:05:54:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource repro-dev/RenderDashpdfsEventSourceMappingSQSPdfstorender: None
[36mlocalstack_1  |[0m 2020-05-21T22:05:54:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False, exists=False, updateable=False): {'Type': 'AWS::Lambda::EventSourceMapping', 'DependsOn': [], 'Properties': {'BatchSize': 10, 'EventSourceArn': 'arn:aws:sqs:us-east-1:000000000000:pdfs-to-render', 'FunctionName': 'arn:aws:lambda:us-east-1:123456789012:function:repro-dev-render-pdfs', 'Enabled': True, 'StartingPosition': 'LATEST'}}
[36mlocalstack_1  |[0m 2020-05-21T22:05:54:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "Lambda::EventSourceMapping" id "RenderDashpdfsEventSourceMappingSQSPdfstorender"
[36mlocalstack_1  |[0m 2020-05-21T22:05:54:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "Lambda::EventSourceMapping" in region us-east-1: create_event_source_mapping {'FunctionName': 'arn:aws:lambda:us-east-1:000000000000:function:repro-dev-render-pdfs', 'EventSourceArn': 'arn:aws:sqs:us-east-1:000000000000:pdfs-to-render', 'StartingPosition': 'LATEST', 'Enabled': True, 'BatchSize': 10}
[36mlocalstack_1  |[0m 2020-05-21T22:05:54:WARNING:localstack.services.cloudformation.cloudformation_starter: Unable to determine physical_resource_id for resource <class 'moto.awslambda.models.EventSourceMapping'>
[36mlocalstack_1  |[0m 2020-05-21T22:05:54:WARNING:localstack.services.cloudformation.cloudformation_starter: Unable to resolve "Ref" attribute for: {'Ref': 'RenderDashpdfsLambdaVersionTqQYalVJPCEUm5jbsO5AqshiuAVsNhivtZ9zyTpeYc'} - RenderDashpdfsLambdaVersionTqQYalVJPCEUm5jbsO5AqshiuAVsNhivtZ9zyTpeYc - <class 'moto.awslambda.models.LambdaVersion'>
[36mlocalstack_1  |[0m 2020-05-21T22:05:54:DEBUG:localstack.services.cloudformation.cloudformation_starter: Running CloudFormation stack deployment loop iteration 1
[36mlocalstack_1  |[0m 2020-05-21T22:06:00:DEBUG:localstack.services.awslambda.lambda_api: Found 1 source mappings for event from SQS queue arn:aws:sqs:us-east-1:000000000000:pdfs-to-render: ['arn:aws:lambda:us-east-1:000000000000:function:repro-dev-render-pdfs']
[36mlocalstack_1  |[0m 2020-05-21T22:06:00:DEBUG:localstack.services.awslambda.lambda_api: Starting SQS message polling thread for Lambda API
[36mlocalstack_1  |[0m 2020-05-21T22:06:00:DEBUG:localstack.services.awslambda.lambda_executors: Lambda executed in Event (asynchronous) mode, no response will be returned to caller
[36mlocalstack_1  |[0m 2020-05-21T22:06:00:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: docker run --user=root --entrypoint=/tmp/localstack/3ccda15a.sh --dns 127.0.0.1 -v /tmp/localstack:/tmp/localstack -i  -v "/tmp/localstack/zipfile.e6719e9b":/var/task -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e HOSTNAME="$HOSTNAME" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e NODE_TLS_REJECT_UNAUTHORIZED="$NODE_TLS_REJECT_UNAUTHORIZED"  --rm "localstack/lambda:nodejs12.x" "pdfs.render"
[36mlocalstack_1  |[0m 2020-05-21T22:06:15:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:repro-dev-render-pdfs result / log output:
[36mlocalstack_1  |[0m {"errorMessage":"2020-05-21T22:06:14.397Z 773988db-dfc1-1fe9-be3a-fb9544f1c7ac Task timed out after 6.00 seconds"}
[36mlocalstack_1  |[0m > WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.
[36mlocalstack_1  |[0m > [32mSTART RequestId: 773988db-dfc1-1fe9-be3a-fb9544f1c7ac Version: $LATEST[0m
[36mlocalstack_1  |[0m > 2020-05-21T22:06:14.393Z	773988db-dfc1-1fe9-be3a-fb9544f1c7ac	ERROR	Error: net::ERR_NAME_NOT_RESOLVED at https://localstack.cloud/
[36mlocalstack_1  |[0m >     at navigate (/var/task/node_modules/puppeteer-core/lib/FrameManager.js:95:23)
[36mlocalstack_1  |[0m >     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[36mlocalstack_1  |[0m >     at async FrameManager.navigateFrame (/var/task/node_modules/puppeteer-core/lib/FrameManager.js:70:21)
[36mlocalstack_1  |[0m >     at async Frame.goto (/var/task/node_modules/puppeteer-core/lib/FrameManager.js:295:16)
[36mlocalstack_1  |[0m >     at async Page.goto (/var/task/node_modules/puppeteer-core/lib/Page.js:476:16)
[36mlocalstack_1  |[0m >     at async Runtime.u [as handler] (/var/task/pdfs.js:1:1414)
[36mlocalstack_1  |[0m >   -- ASYNC --
[36mlocalstack_1  |[0m >     at Frame.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:94:19)
[36mlocalstack_1  |[0m >     at Page.goto (/var/task/node_modules/puppeteer-core/lib/Page.js:476:53)
[36mlocalstack_1  |[0m >     at Page.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:95:27)
[36mlocalstack_1  |[0m >     at Runtime.u [as handler] (/var/task/pdfs.js:1:1422)
[36mlocalstack_1  |[0m >     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[36mlocalstack_1  |[0m > [32mEND RequestId: 773988db-dfc1-1fe9-be3a-fb9544f1c7ac[0m
[36mlocalstack_1  |[0m > [32mREPORT RequestId: 773988db-dfc1-1fe9-be3a-fb9544f1c7ac	Init Duration: 2355.57 ms	Duration: 6000.00 ms	Billed Duration: 6000 ms	Memory Size: 1536 MB	Max Memory Used: 0 MB	[0m
[36mlocalstack_1  |[0m > Starting daemons...
[36mlocalstack_1  |[0m > Starting server loop on UDP port 2000
[36mlocalstack_1  |[0m > Starting DNS server loop on UDP port 53
[36mlocalstack_1  |[0m > Unable to get response from DNS server at 172.17.0.1:53: <class 'socket.error'> [Errno 111] Connection refused
[36mlocalstack_1  |[0m > Unable to get response from DNS server at 172.17.0.1:53: <class 'socket.error'> [Errno 111] Connection refused
[36mlocalstack_1  |[0m > Unable to get response from DNS server at 172.17.0.1:53: <class 'socket.error'> [Errno 111] Connection refused
[36mlocalstack_1  |[0m 2020-05-21T22:06:15:WARNING:bootstrap.py: Thread run method <function LambdaExecutor.execute.<locals>.do_execute at 0x7f07eb533dc0>(None) failed: Traceback (most recent call last):
[36mlocalstack_1  |[0m   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 498, in run
[36mlocalstack_1  |[0m     self.func(self.params)
[36mlocalstack_1  |[0m   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 120, in do_execute
[36mlocalstack_1  |[0m     raise e
[36mlocalstack_1  |[0m   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 108, in do_execute
[36mlocalstack_1  |[0m     result = self._execute(func_arn, func_details, event, context, version)
[36mlocalstack_1  |[0m   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 257, in _execute
[36mlocalstack_1  |[0m     result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
[36mlocalstack_1  |[0m   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 170, in run_lambda_executor
[36mlocalstack_1  |[0m     raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
[36mlocalstack_1  |[0m Exception: Lambda process returned error status code: 1. Result: {"errorMessage":"2020-05-21T22:06:14.397Z 773988db-dfc1-1fe9-be3a-fb9544f1c7ac Task timed out after 6.00 seconds"}. Output:
[36mlocalstack_1  |[0m WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.
[36mlocalstack_1  |[0m [32mSTART RequestId: 773988db-dfc1-1fe9-be3a-fb9544f1c7ac Version: $LATEST[0m
[36mlocalstack_1  |[0m 2020-05-21T22:06:14.393Z	773988db-dfc1-1fe9-be3a-fb9544f1c7ac	ERROR	Error: net::ERR_NAME_NOT_RESOLVED at https://localstack.cloud/
[36mlocalstack_1  |[0m     at navigate (/var/task/node_modules/puppeteer-core/lib/FrameManager.js:95:23)
[36mlocalstack_1  |[0m     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[36mlocalstack_1  |[0m     at async FrameManager.navigateFrame (/var/task/node_modules/puppeteer-core/lib/FrameManager.js:70:21)
[36mlocalstack_1  |[0m     at async Frame.goto (/var/task/node_modules/puppeteer-core/lib/FrameManager.js:295:16)
[36mlocalstack_1  |[0m     at async Page.goto (/var/task/node_modules/puppeteer-core/lib/Page.js:476:16)
[36mlocalstack_1  |[0m     at async Runtime.u [as handler] (/var/task/pdfs.js:1:1414)
[36mlocalstack_1  |[0m   -- ASYNC --
[36mlocalstack_1  |[0m     at Frame.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:94:19)
[36mlocalstack_1  |[0m     at Page.goto (/var/task/node_modules/puppeteer-core/lib/Page.js:476:53)
[36mlocalstack_1  |[0m     at Page.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:95:27)
[36mlocalstack_1  |[0m     at Runtime.u [as handler] (/var/task/pdfs.js:1:1422)
[36mlocalstack_1  |[0m     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[36mlocalstack_1  |[0m [32mEND RequestId: 773988db-dfc1-1fe9-be3a-fb9544f1c7ac[0m
[36mlocalstack_1  |[0m [32mREPORT RequestId: 773988db-dfc1-1fe9-be3a-fb9544f1c7ac	Init Duration: 2355.57 ms	Duration: 6000.00 ms	Billed Duration: 6000 ms	Memory Size: 1536 MB	Max Memory Used: 0 MB	[0m
[36mlocalstack_1  |[0m Starting daemons...
[36mlocalstack_1  |[0m Starting server loop on UDP port 2000
[36mlocalstack_1  |[0m Starting DNS server loop on UDP port 53
[36mlocalstack_1  |[0m Unable to get response from DNS server at 172.17.0.1:53: <class 'socket.error'> [Errno 111] Connection refused
[36mlocalstack_1  |[0m Unable to get response from DNS server at 172.17.0.1:53: <class 'socket.error'> [Errno 111] Connection refused
[36mlocalstack_1  |[0m Unable to get response from DNS server at 172.17.0.1:53: <class 'socket.error'> [Errno 111] Connection refused
[36mlocalstack_1  |[0m 
[36mlocalstack_1  |[0m 
[36mlocalstack_1  |[0m 2020-05-21T22:06:30:DEBUG:localstack.services.awslambda.lambda_executors: Lambda executed in Event (asynchronous) mode, no response will be returned to caller
[36mlocalstack_1  |[0m 2020-05-21T22:06:30:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: docker run --user=root --entrypoint=/tmp/localstack/657d6541.sh --dns 127.0.0.1 -v /tmp/localstack:/tmp/localstack -i  -v "/tmp/localstack/zipfile.e6719e9b":/var/task -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e HOSTNAME="$HOSTNAME" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e NODE_TLS_REJECT_UNAUTHORIZED="$NODE_TLS_REJECT_UNAUTHORIZED"  --rm "localstack/lambda:nodejs12.x" "pdfs.render"
[36mlocalstack_1  |[0m 2020-05-21T22:06:45:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:repro-dev-render-pdfs result / log output:
[36mlocalstack_1  |[0m {"errorMessage":"2020-05-21T22:06:44.374Z 268c63a3-37f6-1540-67d1-1307cf3ccccf Task timed out after 6.00 seconds"}
[36mlocalstack_1  |[0m > WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.
[36mlocalstack_1  |[0m > [32mSTART RequestId: 268c63a3-37f6-1540-67d1-1307cf3ccccf Version: $LATEST[0m
[36mlocalstack_1  |[0m > 2020-05-21T22:06:44.370Z	268c63a3-37f6-1540-67d1-1307cf3ccccf	ERROR	Error: net::ERR_NAME_NOT_RESOLVED at https://localstack.cloud/
[36mlocalstack_1  |[0m >     at navigate (/var/task/node_modules/puppeteer-core/lib/FrameManager.js:95:23)
[36mlocalstack_1  |[0m >     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[36mlocalstack_1  |[0m >     at async FrameManager.navigateFrame (/var/task/node_modules/puppeteer-core/lib/FrameManager.js:70:21)
[36mlocalstack_1  |[0m >     at async Frame.goto (/var/task/node_modules/puppeteer-core/lib/FrameManager.js:295:16)
[36mlocalstack_1  |[0m >     at async Page.goto (/var/task/node_modules/puppeteer-core/lib/Page.js:476:16)
[36mlocalstack_1  |[0m >     at async Runtime.u [as handler] (/var/task/pdfs.js:1:1414)
[36mlocalstack_1  |[0m >   -- ASYNC --
[36mlocalstack_1  |[0m >     at Frame.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:94:19)
[36mlocalstack_1  |[0m >     at Page.goto (/var/task/node_modules/puppeteer-core/lib/Page.js:476:53)
[36mlocalstack_1  |[0m >     at Page.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:95:27)
[36mlocalstack_1  |[0m >     at Runtime.u [as handler] (/var/task/pdfs.js:1:1422)
[36mlocalstack_1  |[0m >     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[36mlocalstack_1  |[0m > [32mEND RequestId: 268c63a3-37f6-1540-67d1-1307cf3ccccf[0m
[36mlocalstack_1  |[0m > [32mREPORT RequestId: 268c63a3-37f6-1540-67d1-1307cf3ccccf	Init Duration: 2383.65 ms	Duration: 6000.00 ms	Billed Duration: 6000 ms	Memory Size: 1536 MB	Max Memory Used: 0 MB	[0m
[36mlocalstack_1  |[0m > Starting daemons...
[36mlocalstack_1  |[0m > Starting server loop on UDP port 2000
[36mlocalstack_1  |[0m > Starting DNS server loop on UDP port 53
[36mlocalstack_1  |[0m > Unable to get response from DNS server at 172.17.0.1:53: <class 'socket.error'> [Errno 111] Connection refused
[36mlocalstack_1  |[0m > Unable to get response from DNS server at 172.17.0.1:53: <class 'socket.error'> [Errno 111] Connection refused
[36mlocalstack_1  |[0m > Unable to get response from DNS server at 172.17.0.1:53: <class 'socket.error'> [Errno 111] Connection refused
[36mlocalstack_1  |[0m 2020-05-21T22:06:45:WARNING:bootstrap.py: Thread run method <function LambdaExecutor.execute.<locals>.do_execute at 0x7f07ec7fd0d0>(None) failed: Traceback (most recent call last):
[36mlocalstack_1  |[0m   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 498, in run
[36mlocalstack_1  |[0m     self.func(self.params)
[36mlocalstack_1  |[0m   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 120, in do_execute
[36mlocalstack_1  |[0m     raise e
[36mlocalstack_1  |[0m   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 108, in do_execute
[36mlocalstack_1  |[0m     result = self._execute(func_arn, func_details, event, context, version)
[36mlocalstack_1  |[0m   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 257, in _execute
[36mlocalstack_1  |[0m     result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
[36mlocalstack_1  |[0m   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 170, in run_lambda_executor
[36mlocalstack_1  |[0m     raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
[36mlocalstack_1  |[0m Exception: Lambda process returned error status code: 1. Result: {"errorMessage":"2020-05-21T22:06:44.374Z 268c63a3-37f6-1540-67d1-1307cf3ccccf Task timed out after 6.00 seconds"}. Output:
[36mlocalstack_1  |[0m WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.
[36mlocalstack_1  |[0m [32mSTART RequestId: 268c63a3-37f6-1540-67d1-1307cf3ccccf Version: $LATEST[0m
[36mlocalstack_1  |[0m 2020-05-21T22:06:44.370Z	268c63a3-37f6-1540-67d1-1307cf3ccccf	ERROR	Error: net::ERR_NAME_NOT_RESOLVED at https://localstack.cloud/
[36mlocalstack_1  |[0m     at navigate (/var/task/node_modules/puppeteer-core/lib/FrameManager.js:95:23)
[36mlocalstack_1  |[0m     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[36mlocalstack_1  |[0m     at async FrameManager.navigateFrame (/var/task/node_modules/puppeteer-core/lib/FrameManager.js:70:21)
[36mlocalstack_1  |[0m     at async Frame.goto (/var/task/node_modules/puppeteer-core/lib/FrameManager.js:295:16)
[36mlocalstack_1  |[0m     at async Page.goto (/var/task/node_modules/puppeteer-core/lib/Page.js:476:16)
[36mlocalstack_1  |[0m     at async Runtime.u [as handler] (/var/task/pdfs.js:1:1414)
[36mlocalstack_1  |[0m   -- ASYNC --
[36mlocalstack_1  |[0m     at Frame.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:94:19)
[36mlocalstack_1  |[0m     at Page.goto (/var/task/node_modules/puppeteer-core/lib/Page.js:476:53)
[36mlocalstack_1  |[0m     at Page.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:95:27)
[36mlocalstack_1  |[0m     at Runtime.u [as handler] (/var/task/pdfs.js:1:1422)
[36mlocalstack_1  |[0m     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[36mlocalstack_1  |[0m [32mEND RequestId: 268c63a3-37f6-1540-67d1-1307cf3ccccf[0m
[36mlocalstack_1  |[0m [32mREPORT RequestId: 268c63a3-37f6-1540-67d1-1307cf3ccccf	Init Duration: 2383.65 ms	Duration: 6000.00 ms	Billed Duration: 6000 ms	Memory Size: 1536 MB	Max Memory Used: 0 MB	[0m
[36mlocalstack_1  |[0m Starting daemons...
[36mlocalstack_1  |[0m Starting server loop on UDP port 2000
[36mlocalstack_1  |[0m Starting DNS server loop on UDP port 53
[36mlocalstack_1  |[0m Unable to get response from DNS server at 172.17.0.1:53: <class 'socket.error'> [Errno 111] Connection refused
[36mlocalstack_1  |[0m Unable to get response from DNS server at 172.17.0.1:53: <class 'socket.error'> [Errno 111] Connection refused
[36mlocalstack_1  |[0m Unable to get response from DNS server at 172.17.0.1:53: <class 'socket.error'> [Errno 111] Connection refused
[36mlocalstack_1  |[0m 
[36mlocalstack_1  |[0m 
[36mlocalstack_1  |[0m 2020-05-21T22:07:01:DEBUG:localstack.services.awslambda.lambda_executors: Lambda executed in Event (asynchronous) mode, no response will be returned to caller
[36mlocalstack_1  |[0m 2020-05-21T22:07:01:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: docker run --user=root --entrypoint=/tmp/localstack/ce234dcd.sh --dns 127.0.0.1 -v /tmp/localstack:/tmp/localstack -i  -v "/tmp/localstack/zipfile.e6719e9b":/var/task -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e HOSTNAME="$HOSTNAME" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e NODE_TLS_REJECT_UNAUTHORIZED="$NODE_TLS_REJECT_UNAUTHORIZED"  --rm "localstack/lambda:nodejs12.x" "pdfs.render"
[36mlocalstack_1  |[0m 2020-05-21T22:07:16:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:repro-dev-render-pdfs result / log output:
[36mlocalstack_1  |[0m {"errorMessage":"2020-05-21T22:07:15.151Z 502046d4-67da-1c71-c58b-3f4200cc88da Task timed out after 6.00 seconds"}
[36mlocalstack_1  |[0m > WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.
[36mlocalstack_1  |[0m > [32mSTART RequestId: 502046d4-67da-1c71-c58b-3f4200cc88da Version: $LATEST[0m
[36mlocalstack_1  |[0m > 2020-05-21T22:07:15.147Z	502046d4-67da-1c71-c58b-3f4200cc88da	ERROR	Error: net::ERR_NAME_NOT_RESOLVED at https://localstack.cloud/
[36mlocalstack_1  |[0m >     at navigate (/var/task/node_modules/puppeteer-core/lib/FrameManager.js:95:23)
[36mlocalstack_1  |[0m >     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[36mlocalstack_1  |[0m >     at async FrameManager.navigateFrame (/var/task/node_modules/puppeteer-core/lib/FrameManager.js:70:21)
[36mlocalstack_1  |[0m >     at async Frame.goto (/var/task/node_modules/puppeteer-core/lib/FrameManager.js:295:16)
[36mlocalstack_1  |[0m >     at async Page.goto (/var/task/node_modules/puppeteer-core/lib/Page.js:476:16)
[36mlocalstack_1  |[0m >     at async Runtime.u [as handler] (/var/task/pdfs.js:1:1414)
[36mlocalstack_1  |[0m >   -- ASYNC --
[36mlocalstack_1  |[0m >     at Frame.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:94:19)
[36mlocalstack_1  |[0m >     at Page.goto (/var/task/node_modules/puppeteer-core/lib/Page.js:476:53)
[36mlocalstack_1  |[0m >     at Page.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:95:27)
[36mlocalstack_1  |[0m >     at Runtime.u [as handler] (/var/task/pdfs.js:1:1422)
[36mlocalstack_1  |[0m >     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[36mlocalstack_1  |[0m > [32mEND RequestId: 502046d4-67da-1c71-c58b-3f4200cc88da[0m
[36mlocalstack_1  |[0m > [32mREPORT RequestId: 502046d4-67da-1c71-c58b-3f4200cc88da	Init Duration: 2345.37 ms	Duration: 6000.00 ms	Billed Duration: 6000 ms	Memory Size: 1536 MB	Max Memory Used: 0 MB	[0m
[36mlocalstack_1  |[0m > Starting daemons...
[36mlocalstack_1  |[0m > Starting server loop on UDP port 2000
[36mlocalstack_1  |[0m > Starting DNS server loop on UDP port 53
[36mlocalstack_1  |[0m > Unable to get response from DNS server at 172.17.0.1:53: <class 'socket.error'> [Errno 111] Connection refused
[36mlocalstack_1  |[0m > Unable to get response from DNS server at 172.17.0.1:53: <class 'socket.error'> [Errno 111] Connection refused
[36mlocalstack_1  |[0m > Unable to get response from DNS server at 172.17.0.1:53: <class 'socket.error'> [Errno 111] Connection refused
[36mlocalstack_1  |[0m 2020-05-21T22:07:16:WARNING:bootstrap.py: Thread run method <function LambdaExecutor.execute.<locals>.do_execute at 0x7f07eb533dc0>(None) failed: Traceback (most recent call last):
[36mlocalstack_1  |[0m   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 498, in run
[36mlocalstack_1  |[0m     self.func(self.params)
[36mlocalstack_1  |[0m   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 120, in do_execute
[36mlocalstack_1  |[0m     raise e
[36mlocalstack_1  |[0m   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 108, in do_execute
[36mlocalstack_1  |[0m     result = self._execute(func_arn, func_details, event, context, version)
[36mlocalstack_1  |[0m   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 257, in _execute
[36mlocalstack_1  |[0m     result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
[36mlocalstack_1  |[0m   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 170, in run_lambda_executor
[36mlocalstack_1  |[0m     raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
[36mlocalstack_1  |[0m Exception: Lambda process returned error status code: 1. Result: {"errorMessage":"2020-05-21T22:07:15.151Z 502046d4-67da-1c71-c58b-3f4200cc88da Task timed out after 6.00 seconds"}. Output:
[36mlocalstack_1  |[0m WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.
[36mlocalstack_1  |[0m [32mSTART RequestId: 502046d4-67da-1c71-c58b-3f4200cc88da Version: $LATEST[0m
[36mlocalstack_1  |[0m 2020-05-21T22:07:15.147Z	502046d4-67da-1c71-c58b-3f4200cc88da	ERROR	Error: net::ERR_NAME_NOT_RESOLVED at https://localstack.cloud/
[36mlocalstack_1  |[0m     at navigate (/var/task/node_modules/puppeteer-core/lib/FrameManager.js:95:23)
[36mlocalstack_1  |[0m     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[36mlocalstack_1  |[0m     at async FrameManager.navigateFrame (/var/task/node_modules/puppeteer-core/lib/FrameManager.js:70:21)
[36mlocalstack_1  |[0m     at async Frame.goto (/var/task/node_modules/puppeteer-core/lib/FrameManager.js:295:16)
[36mlocalstack_1  |[0m     at async Page.goto (/var/task/node_modules/puppeteer-core/lib/Page.js:476:16)
[36mlocalstack_1  |[0m     at async Runtime.u [as handler] (/var/task/pdfs.js:1:1414)
[36mlocalstack_1  |[0m   -- ASYNC --
[36mlocalstack_1  |[0m     at Frame.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:94:19)
[36mlocalstack_1  |[0m     at Page.goto (/var/task/node_modules/puppeteer-core/lib/Page.js:476:53)
[36mlocalstack_1  |[0m     at Page.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:95:27)
[36mlocalstack_1  |[0m     at Runtime.u [as handler] (/var/task/pdfs.js:1:1422)
[36mlocalstack_1  |[0m     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[36mlocalstack_1  |[0m [32mEND RequestId: 502046d4-67da-1c71-c58b-3f4200cc88da[0m
[36mlocalstack_1  |[0m [32mREPORT RequestId: 502046d4-67da-1c71-c58b-3f4200cc88da	Init Duration: 2345.37 ms	Duration: 6000.00 ms	Billed Duration: 6000 ms	Memory Size: 1536 MB	Max Memory Used: 0 MB	[0m
[36mlocalstack_1  |[0m Starting daemons...
[36mlocalstack_1  |[0m Starting server loop on UDP port 2000
[36mlocalstack_1  |[0m Starting DNS server loop on UDP port 53
[36mlocalstack_1  |[0m Unable to get response from DNS server at 172.17.0.1:53: <class 'socket.error'> [Errno 111] Connection refused
[36mlocalstack_1  |[0m Unable to get response from DNS server at 172.17.0.1:53: <class 'socket.error'> [Errno 111] Connection refused
[36mlocalstack_1  |[0m Unable to get response from DNS server at 172.17.0.1:53: <class 'socket.error'> [Errno 111] Connection refused
[36mlocalstack_1  |[0m 
[36mlocalstack_1  |[0m 
Stopping repro_localstack_1 ... 
[1A[2KStopping repro_localstack_1 ... [32mdone[0m[1BGracefully stopping... (press Ctrl+C again to force)
